### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by mattmattox** [Orange-OpenSource/galera-operator#22]
I would like to use this project for managing my Galera MariaDB clusters at scale. But it looks like this project has gone quiet.

I have deployed the operator on v1.21.5+rke2r1, but it looks like the GO library is out-of-date; just go panics.

```
fatal error: mlock failed

runtime stack:
runtime.throw(0x144afb9, 0xc)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:1112 +0x72
runtime.mlockGsignal(0xc000622d80)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/os_linux_x86.go:72 +0x107
runtime.mpreinit(0xc0004a8a80)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/os_linux.go:341 +0x78
runtime.mcommoninit(0xc0004a8a80)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:630 +0x108
runtime.allocm(0xc000068000, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:1390 +0x14e
runtime.newm(0x0, 0xc000068000)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:1704 +0x39
runtime.startm(0x0, 0x100000000)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:1869 +0x12a
runtime.injectglist(0xc000357e98)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:2439 +0x13f
runtime.findrunnable(0xc00004a000, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:2128 +0xc9c
runtime.schedule()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:2520 +0x2fc
runtime.park_m(0xc000622c00)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:2690 +0x9d
runtime.mcall(0x0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:318 +0x5b

goroutine 1 [chan receive]:
main.main()
	/Users/seb/dev/galera/galera-operator/cmd/galera-operator/main.go:190 +0xf9b

goroutine 6 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x1fd20e0)
	/Users/seb/dev/galera/galera-operator/vendor/k8s.io/klog/klog.go:990 +0x8b
created by k8s.io/klog.init.0
	/Users/seb/dev/galera/galera-operator/vendor/k8s.io/klog/klog.go:404 +0x6c

goroutine 14 [chan receive]:
k8s.io/client-go/tools/cache.(*sharedProcessor).run(0xc0001f5500, 0xc000246000)
	/Users/seb/dev/galera/galera-operator/vendor/k8s.io/client-go/tools/cache/shared_informer.go:478 +0x53
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/Users/seb/dev/galera/galera-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:54 +0x2e
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000046490, 0xc0002625a0)
	/Users/seb/dev/galera/galera-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/Users/seb/dev/galera/galera-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62

goroutine 52 [IO wait]:
internal/poll.runtime_pollWait(0x7fcc0b01af18, 0x72, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc000048098, 0x72, 0x0, 0x0, 0x1446fe8)
	/usr/local/Cellar/go/1.14/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.14/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000048080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/internal/poll/fd_unix.go:384 +0x1d4
net.(*netFD).accept(0xc000048080, 0xc00001cda8, 0xc000100000, 0x7fcc31ce7108)
	/usr/local/Cellar/go/1.14/libexec/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0002624a0, 0xc00001cde8, 0x40c858, 0x30)
	/usr/local/Cellar/go/1.14/libexec/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0002624a0, 0x1389420, 0xc000232fc0, 0x1293a00, 0x1fbd900)
	/usr/local/Cellar/go/1.14/libexec/src/net/tcpsock.go:261 +0x64
net/http.(*Server).Serve(0xc0001d01c0, 0x164efe0, 0xc0002624a0, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/net/http/server.go:2901 +0x25d
net/http.(*Server).ListenAndServe(0xc0001d01c0, 0xc0001d01c0, 0xc000075fb8)
	/usr/local/Cellar/go/1.14/libexec/src/net/http/server.go:2830 +0xb7
net/http.ListenAndServe(0x1445e64, 0x5, 0x0, 0x0, 0x1ffba78, 0x203000)
	/usr/local/Cellar/go/1.14/libexec/src/net/http/server.go:3086 +0x74
created by main.main
	/Users/seb/dev/galera/galera-operator/cmd/galera-operator/main.go:99 +0x47b
```

**Comment by sebs42** [comment]
This project is not active, I tried to open-source and to have some help on it but it seems galera clusters are not very used. I can put an upgrade about upcoming K8S 1.22 because CRD in v1beta1 will be deprecated with this new version. It will be built using golang 1.15.6

If you plan to use it, keep in mind that you will have to maintain the operator.
